### ISSUE TITLE
encountering an issue while creating the binlist.

### ISSUE THREAD

**Issue by lixianrui999** [ucdavis/erplab#175]
When I use ERPLAB to load a Binlist, I encountered an issue, and it displayed as the following error: 
Parsing Bin Descriptor File and creating BIN structure...
Error Line 7 BIN 2 : time condition should be declared one time, and at the beginning of the sequencer
...
Line 7 Error Resume: 
Line 7 has 1 errors during syntax parsing.... 
HINT:
.{1;4;51;54}{5;t<500-2000>2}
..............X.............

I previously created the Binlist in this way：
bin1
intero_anger
.{1;4;51;54}{t<500-2000>5;t<500-2000>2}，

In this Binlist, I want to restrict the time window for response markers 2 or 5.
As suggested by the error message, I made the following changes:
bin1
intero_anger
.{1;4;51;54}{t<500-2000>5;2}，

Could you please confirm if they are correct?
thanks！

**Comment by davidg622** [comment]
Hello Xianrui Li,

Thanks for your question!

I reviewed your bin, and it looks like it should now correctly bin response markers 2 and 5 if they are between 500-2000 after markers 1,4,51,54. Feel free to review our documentation at https://github.com/ucdavis/erplab/wiki/BDF-Library if you have more questions.

Thanks,

David
