### ISSUE TITLE
Binlister error

### ISSUE THREAD

**Issue by pb865** [ucdavis/erplab#187]
### Description

While trying to use the binlister, two errors are returned:

```Operands to the logical AND (&&) and OR (||) operators must be convertible to logical scalar values. Use the ANY or ALL functions to reduce operands to logical scalar values.

Error in neobinlister2 (line 280)
        cd1 = EVENTLIST.eventinfo(iLogitem).enable~=-1 && ~ismember(EVENTLIST.eventinfo(iLogitem).code, forbiddenCodeArray);

Error in pop_binlister (line 436)
        [EEG, EVENTLIST, binofbins, isparsenum] = neobinlister2(EEG, file1, file2, file3, forbiddenCodeArray, ignoreCodeArray, 0);
```

```EEG``` refers to the EEG file I am trying to process. This set is part of a preprocessing for-loop I have written. The line of code that produces this error is:

``` 
EEG  = pop_binlister( EEG , 'BDF', [DIR1 '/' 'WIT_key_bins_v3.txt'], 'ExportEL', [DIR3 '/' SUB{i} '_WIT_eventlist_bins.txt'], 'IndexEL',  1, 'SendEL2', 'EEG&Text', 'UpdateEEG', 'on', 'Voutput', 'EEG' );
```

Where ```EEG``` is my EEG file, ``DIR1``` is the directory to where the binlister txt file is, and DIR3 is the output directory. 

My binlister text file looks like this:

bin 1

BPG_Correct

.{15}

bin 2

BPG_Incorrect

.{16}

bin 3

BPT_Correct

.{18}

bin 4

BPT_Incorrect

.{19}

bin 5

WPG_Correct

.{24}

bin 6

WPG_Incorrect

.{25}

bin 7

WPT_Correct

.{27}

bin 8

WPT_Incorrect

.{28}

"AND" and "OR" do not apply in terms of my bins, so I'm not quite sure to what this error is referring. 

  

<br>
#### Expected behavior:

Bin the events based on my binlister .txt file.

<br>
#### Actual behavior:
Errors returned. Could not complete preprocessing. 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 11 Education version 23H2] |
| Matlab version | [23.2.0.2365128 (R2023b)] |
| EEGLAB version | [2023.0] |
| ERPLAB version | [v10.0] |

**Comment by davidg622** [comment]
Hello,

Does the same error occur when you use Binlister through the GUI? If so, please send me a sample of your data and the Binlister file to my email address, drgarrett@ucdavis.edu, where I can try to diagnose the problem.

Thanks,
David
